# Site settings
title: KingXt Blog
SEOTitle: KingXt Blog
header-img: img/home-bg.jpg
description: "懂点代码"
keyword: "KingXt"
url: "http://kingxt.me"



# SNS settings
RSS: false
weibo_username:     2531664240
github_username:    kingxt

# Build settings
highlighter: rouge
pygments: true
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Build settings

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写代码是会上瘾的。"
sidebar-avatar: /img/avatar.jpeg     # use absolute URL.



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value
